# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key C-f display-popup -E "~/.local/scripts/tmux-sessionizer/tmux-sessionizer"

set -g mouse on
set -g history-limit 10000
set -g allow-rename off

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# Neovim settings
set -g escape-time 10
set -g focus-events on
set -g default-terminal "screen-256color"
# set -sa terminal-features ',xterm-256color:RGB'
set -ga terminal-overrides ',xterm-256color:Tc'

# loud or quiet?
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

set-window-option -g mode-keys vi
set-option -sa terminal-overrides ",xterm*:Tc"

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_window_current_text "[#{window_name}]"
set -g @catppuccin_window_default_text "#{window_name}"

# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-restore 'on'

set -g @plugin 'laktak/extrakto'

# prefix + I -> install plugins

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
