# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display "Configuration reloaded"

# Vi mode for copy
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Pane Controls
bind h split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind x kill-pane

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n C-M-S-Left resize-pane -L 5
bind -n C-M-S-Down resize-pane -D 5
bind -n C-M-S-Up resize-pane -U 5
bind -n C-M-S-Right resize-pane -R 5

# Session controls
bind R command-prompt -I "#S" "rename-session -- '%%'"
bind C new-session -c "#{pane_current_path}"
bind K kill-session
bind P switch-client -p
bind N switch-client -n

bind -n M-Up switch-client -p
bind -n M-Down switch-client -n

bind-key C-f display-popup -E "~/.local/scripts/tmux-sessionizer/tmux-sessionizer"

set -g mouse on
set -g history-limit 50000
set -g allow-rename off

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# Neovim settings
set -g escape-time 10
set -g focus-events on
set -g default-terminal "screen-256color"
# set -sa terminal-features ',xterm-256color:RGB'
# set -ga terminal-overrides ',xterm-256color:Tc'
set -ag terminal-overrides ",*:RGB"

# loud or quiet?
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# set-option -sa terminal-overrides ",xterm*:Tc"

# Status bar
set -g status-position bottom
set -g status-interval 5
set -g status-left-length 30
set -g status-right-length 50
set -g window-status-separator ""
set -gw automatic-rename on
set -gw automatic-rename-format '#{b:pane_current_path}'


if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_window_current_text "[#{window_name}]"
set -g @catppuccin_window_default_text "#{window_name}"

# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-restore 'on'

set -g @plugin 'laktak/extrakto'

# prefix + I -> install plugins

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
